name: virtuo
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  bloc: ^8.1.0
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.1.0
#  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  file_picker: ^5.2.2
  firebase_analytics: ^10.0.6
  firebase_app_check: ^0.1.1+5
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6
  firebase_messaging: ^14.1.2
  firebase_storage: ^11.0.6
  flutter_bloc: ^8.1.1
  flutter_cache_manager: ^3.3.0
  flutter_image_compress: ^1.1.3
  flutter_local_notifications: ^12.0.4
  flutter_native_image: ^0.0.6+1
  flutter_svg: ^1.1.6
  image_picker: ^0.8.6
  image_size_getter: ^2.1.2
  intl: ^0.17.0
  logger: ^1.1.0
  meta: ^1.8.0
  overlay_support: ^2.1.0
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  pin_code_fields: ^7.4.0
  qr_code_scanner: ^1.0.1
    #  qr_flutter:
  restart_app: ^1.1.0+1
  url_launcher: ^6.1.7
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  simple_animations: ^5.0.0+3
  get: ^4.6.1
  lottie: ^2.1.0
  accordion: ^2.5.1
  quickalert: ^1.0.1
  pdf_compressor: ^0.2.0
  rxdart: ^0.27.2
  dio: ^5.0.2
  flutter_pdfview: ^1.2.5
  google_fonts: ^4.0.3
  firebase_auth: ^4.2.9
  fluttertoast: ^8.2.1
  shimmer: ^2.0.0
  shared_preferences: ^2.0.18
  flutter_rating_bar: ^4.0.1
  flutter_unity_widget:
  http:
  printing:
  flutter_slidable:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/virtuo_logo.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
